# Generated by Django 4.1.5 on 2023-02-05 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_exercises_delete_training"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("muscles", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("muscles", models.ImageField(upload_to="photos/%Y/%m/%d")),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=128)),
                ("date_of_birth", models.DateField()),
                ("like_exercises", models.TextField(blank=True)),
                (
                    "trainings",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.training",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Exercises",),
        migrations.AddField(
            model_name="training",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="training.users",
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="exercises",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="name",
                to="training.exercise",
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="train_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="training.exercise",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="train",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="training.training",
            ),
        ),
    ]
