# Generated by Django 4.1.5 on 2023-02-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_exercise_training_users_delete_exercises_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="training", old_name="title", new_name="train_name",
        ),
    ]
