# Generated by Django 4.1.5 on 2023-04-20 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание упражнения"),
                ),
                (
                    "muscles_photo",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="Группа мышц"
                    ),
                ),
            ],
            options={
                "verbose_name": "Упражнения",
                "verbose_name_plural": "Упражнения",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Muscles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "muscles_name",
                    models.CharField(
                        max_length=255, verbose_name="Название группы мышц"
                    ),
                ),
            ],
            options={
                "verbose_name": "Мышцы",
                "verbose_name_plural": "Мышцы",
                "ordering": ["muscles_name"],
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=128, verbose_name="Имя пользователя"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                ("weight", models.IntegerField(null=True, verbose_name="Вес")),
                ("height", models.IntegerField(null=True, verbose_name="Рост")),
                (
                    "email",
                    models.EmailField(max_length=128, null=True, verbose_name="Почта"),
                ),
            ],
            options={
                "verbose_name": "Пользователи",
                "verbose_name_plural": "Пользователи",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "train_name",
                    models.CharField(
                        max_length=255, verbose_name="Название тренировки"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Содержание тренировки"),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.users",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "exercises",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.exercise",
                        verbose_name="Упражнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренировки",
                "verbose_name_plural": "Тренировки",
                "ordering": ["time_created"],
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="muscles_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="training.muscles",
                verbose_name="Упражнения на мышцы",
            ),
        ),
    ]
