# Generated by Django 4.1.5 on 2023-05-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_remove_training_exercises_training_exercises"),
    ]

    operations = [
        migrations.RemoveField(model_name="training", name="author",),
        migrations.DeleteModel(name="Users",),
    ]
