# Generated by Django 4.1.5 on 2023-05-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0006_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="training.profile",
                verbose_name="Автор",
            ),
        ),
    ]
