# Generated by Django 4.1.5 on 2023-05-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0009_alter_training_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Персональная ссылка",
            ),
        ),
    ]
