# Generated by Django 4.1.5 on 2023-05-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0010_profile_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="slug",),
    ]
